#!/bin/bash
# Copyright 2019-2022 Alibaba Group Holding Limited.
# SPDX-License-Identifier: GPL-2.0 OR BSD-3-Clause

TEST_PATH=$(realpath $(dirname "$0"))
cd ${TEST_PATH}
export PATH=$PATH:${TEST_PATH}
