#!/bin/bash
# Copyright 2019-2022 Alibaba Group Holding Limited.
# SPDX-License-Identifier: GPL-2.0 OR BSD-3-Clause

source $(dirname "$0")/libs/working_dir
source libs/catch_error

tests=$(cat bundles/$1)
prep_env
for T in ${tests}; do
	build_case test_$T
	test_$T/assert
done
