#!/usr/bin/env python3
# Copyright 2019-2022 Alibaba Group Holding Limited.
# SPDX-License-Identifier: GPL-2.0 OR BSD-3-Clause

import subprocess
import sh
import os
import sys
import time
from glob import glob

class TestCPUThrottle:
    def setup_class(self):
        self.test_flag = True
        print("CPU throttle test")
        sh.mkdir('/sys/fs/cgroup/cpu/test')
        
    def init_cgroup(self):
        cmd = "while :; do :; done"
        self.start_time = time.time()
        self.child = subprocess.Popen(cmd, shell=True)
        sh.echo(self.child.pid, _out='/sys/fs/cgroup/cpu/test/cgroup.procs')

    def set_cfs_quota(self, t_us):
        sh.echo(t_us, _out='/sys/fs/cgroup/cpu/test/cpu.cfs_quota_us')
        time.sleep(10)

    def test_all(self):
        self.set_cfs_quota('50000')
        self.init_cgroup()
        self.check_le_75()
        self.check_after_load()
        self.set_cfs_quota('100000')
        self.check_gt_75()
        self.check_after_unload()
        
    def check_le_75(self):
        cpu_util = self.get_cpu_util(self.child.pid)
        # assert cpu_util <= 75
        if cpu_util > 75:
            self.error_handler(0, 75)

    def check_after_load(self):
        scheduler_rpm = glob(os.path.join('/tmp/work', 'scheduler*.rpm'))
        if len(scheduler_rpm) != 1:
            print("Please check your scheduler rpm");
            self.teardown_class()
            sys.exit(1)
        scheduler_rpm = scheduler_rpm[0]
        sh.rpm('-ivh', scheduler_rpm)
        cpu_util = self.get_cpu_util(self.child.pid)
        # assert cpu_util <= 75
        if cpu_util > 75:
            self.error_handler(0, 75)

    def check_gt_75(self):
        cpu_util = self.get_cpu_util(self.child.pid)
        # assert cpu_util >= 75
        if cpu_util < 75:
            self.error_handler(1, 75)

    def check_after_unload(self):
        sh.rpm('-e', 'scheduler-xxx')
        cpu_util = self.get_cpu_util(self.child.pid)
        # assert cpu_util >= 75
        if cpu_util < 75:
            self.error_handler(1, 75)

    def get_cpu_util(self, pid):
        def cpu_usage():
            time.sleep(0.5)
            herts = float(sh.getconf('CLK_TCK'))
            process_file = "/proc/" + str(pid) + "/stat"
            process_stat = sh.cat(process_file).split()
            total_time = float(process_stat[13]) + float(process_stat[14])
            elapsed_seconds = time.time() - self.start_time
            return 100.0 * ((total_time / herts) / elapsed_seconds)
        
        cpu_util_1 = cpu_usage()
        cpu_util_2 = cpu_usage()
        cpu_util = (cpu_util_1 + cpu_util_2) / 2
        return cpu_util

    def teardown_class(self):
        self.child.kill()
        self.child.wait()
        sh.rmdir("/sys/fs/cgroup/cpu/test")
        tmp = subprocess.Popen("lsmod | grep scheduler", shell=True, stdout=subprocess.PIPE)
        if tmp.stdout.read() != b'':
            sh.rpm('-e', 'scheduler-xxx')

    def error_handler(self, ty, bound):
        err_msg = "CPU util should " + ("less than" if ty == 0 else "greater than") + str(bound)
        print(err_msg)
        self.teardown_class()
        sys.exit(1)


if __name__ == '__main__':
    test_unit = TestCPUThrottle()
    test_unit.setup_class()
    test_unit.test_all()
    test_unit.teardown_class()
