/* This file defines functions need to jump to funcs in plugsched */

EXPORT_PLUGSCHED(do_set_cpus_allowed, void, struct task_struct *,
		 const struct cpumask *)
EXPORT_PLUGSCHED(set_user_nice, void, struct task_struct *, long)
EXPORT_PLUGSCHED(sched_setscheduler, int, struct task_struct *, int,
		 const struct sched_param *)
EXPORT_PLUGSCHED(sched_setscheduler_nocheck, int, struct task_struct *, int,
		 const struct sched_param *)
EXPORT_PLUGSCHED(__set_cpus_allowed_ptr, int, struct task_struct *, const struct cpumask *, bool)
EXPORT_PLUGSCHED(schedule_tail, void, struct task_struct *)
EXPORT_PLUGSCHED(scheduler_tick, void, void)
EXPORT_PLUGSCHED(sched_fork, int, unsigned long, struct task_struct *)
EXPORT_PLUGSCHED(scheduler_ipi, void, void)
EXPORT_PLUGSCHED(__schedule, void, bool)
EXPORT_PLUGSCHED(resched_cpu, void, int)
EXPORT_PLUGSCHED(task_rq_lock, struct rq *, struct task_struct *,
		 struct rq_flags *)
EXPORT_PLUGSCHED(get_nohz_timer_target, int, void)
EXPORT_PLUGSCHED(nohz_balance_enter_idle, void, int)
EXPORT_PLUGSCHED(sched_ttwu_pending, void, void)
EXPORT_PLUGSCHED(wake_up_if_idle, void, int)
EXPORT_PLUGSCHED(try_to_wake_up, int, struct task_struct *, unsigned int, int)
EXPORT_PLUGSCHED(wake_up_new_task, void, struct task_struct *)
EXPORT_PLUGSCHED(wake_up_nohz_cpu, void, int)
EXPORT_PLUGSCHED(rt_mutex_setprio, void, struct task_struct *,
		 struct task_struct *)
EXPORT_PLUGSCHED(idle_cpu, int, int)
EXPORT_PLUGSCHED(partition_sched_domains, void, int, cpumask_var_t *,
		 struct sched_domain_attr *)
EXPORT_PLUGSCHED(sched_set_stop_task, void, int, struct task_struct *)
EXPORT_PLUGSCHED(task_numa_group_id, pid_t, struct task_struct *)
EXPORT_PLUGSCHED(should_numa_migrate_memory, bool, struct task_struct *,
		 struct page *, int, int)
EXPORT_PLUGSCHED(task_numa_free, void, struct task_struct *, bool)
EXPORT_PLUGSCHED(task_numa_fault, void, int, int, int, int)
EXPORT_PLUGSCHED(proc_sched_show_task, void, struct task_struct *, struct seq_file *)
EXPORT_PLUGSCHED(proc_sched_set_task, void, struct task_struct *)
EXPORT_PLUGSCHED(init_idle, void, struct task_struct *, int)
EXPORT_PLUGSCHED(release_task_reserve, void, struct task_struct *)
EXPORT_PLUGSCHED(init_task_reserve, void, struct task_struct *, bool)
EXPORT_PLUGSCHED(in_sched_functions, int, unsigned long)
EXPORT_PLUGSCHED(task_sched_runtime, unsigned long long, struct task_struct *)
EXPORT_PLUGSCHED(cpuset_cpumask_can_shrink, int, const struct cpumask *, const struct cpumask *)
EXPORT_PLUGSCHED(task_can_attach, int, struct task_struct *, const struct cpumask *)
EXPORT_PLUGSCHED(normalize_rt_tasks, void, void)
EXPORT_PLUGSCHED(sysrq_sched_debug_show, void, void)
EXPORT_PLUGSCHED(sched_move_task, void, struct task_struct *)
EXPORT_PLUGSCHED(sched_group_set_shares, int, struct task_group *, unsigned long)
EXPORT_PLUGSCHED(sched_offline_group, void, struct task_group *)
EXPORT_PLUGSCHED(sched_destroy_group, void, struct task_group *)
EXPORT_PLUGSCHED(sched_create_group, struct task_group *, struct task_group *)
EXPORT_PLUGSCHED(sched_online_group, void, struct task_group *, struct task_group *)
EXPORT_PLUGSCHED(id_nr_invalid, unsigned int, struct rq *)
EXPORT_PLUGSCHED(finish_task_switch, struct rq *, struct task_struct *)
