commit 24001925bf1bf01152e61f471d9d3812940388cf
Author: Yihao Wu <wuyihao@linux.alibaba.com>
Date:   Sat Dec 12 16:55:09 2020 +0800
    
    Signed-off-by: Shanpei Chen <shanpei.csp@alibaba-inc.com>
    Signed-off-by: Erwei Deng <erwei@linux.alibaba.com>
    Signed-off-by: Yihao Wu <wuyihao@linux.alibaba.com>

diff --git a/scripts/Makefile.build b/scripts/Makefile.build
index 64fac0a..eadcce4 100644
--- a/scripts/Makefile.build
+++ b/scripts/Makefile.build
@@ -298,10 +298,20 @@ else
 cmd_undef_syms = echo
 endif
 
+ifneq ($(strip $(SCHED_MOD_STAGE)),)
+SCHED_MOD_CFLAGS := -fplugin=../gcc-python-plugin/python.so \
+                    -fplugin-arg-python-script=sched_boundary.py	    \
+                    -fplugin-arg-python-stage=$(SCHED_MOD_STAGE)
+cmd_sched_boundary_cc_o_c = $(cmd_cc_o_c) $(SCHED_MOD_CFLAGS)
+$(obj)/%.o: $(src)/%.c FORCE
+	$(call cmd,force_checksrc)
+	$(call cmd,sched_boundary_cc_o_c)
+else
 # Built-in and composite module parts
 $(obj)/%.o: $(src)/%.c $(recordmcount_source) $(objtool_dep) FORCE
 	$(call cmd,force_checksrc)
 	$(call if_changed_rule,cc_o_c)
+endif
 
 # Single-part modules are special since we need to mark them in $(MODVERDIR)
 

