#!/bin/bash

cursys=$(uname -r)
modfile=/var/plugsched/$cursys/plugsched.ko
mod=$(modinfo $modfile | grep vermagic | awk '{print $2}')

skip="/var/plugsched/skip"
if [ -f "$skip" ]; then
	echo "Error: plugsched: cannot load plugsched, please update"
	exit 1
fi

if ! /usr/local/bin/plugsched-verses-kpatch.py pre; then
	echo "Error: there are hotfixes conflicting with plugsched. Exit."
	exit 1
fi

if [ "$cursys" == "$mod" ]; then
	/usr/bin/cp $modfile /run/plugsched/plugsched.ko
	/usr/local/bin/plugsched /run/plugsched/plugsched.ko /proc/kallsyms
	/usr/bin/touch $skip
	/usr/bin/sync
	/usr/sbin/insmod /run/plugsched/plugsched.ko
	/usr/bin/rm -f $skip
else
	echo "Error: kernel version is not same as plugsched version!"
	exit 1
fi

