#!/bin/bash

cursys=$(uname -r)
modfile=/var/plugsched/$cursys/scheduler.ko
mod=$(modinfo $modfile | grep vermagic | awk '{print $2}')

if [ "$cursys" == "$mod" ]; then
	/usr/bin/cp $modfile /run/plugsched/scheduler.ko
	/usr/local/bin/symbol_resolve /run/plugsched/scheduler.ko /proc/kallsyms
	/usr/sbin/insmod /run/plugsched/scheduler.ko
else
	echo "Error: kernel version is not same as plugsched version!"
	exit 1
fi
